version: '3.9'

services:
  app:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
      args:
        USER_NAME: ${USER_NAME}
        USER_UID: ${USER_UID}
        env_file: .env
    working_dir: /var/www/data_structures/
    volumes:
      - type: bind
        source: ./app
        target: /var/www/data_structures/
